"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { DashboardBackLink } from "@/components/navigation/DashboardBackLink";
import { generateTasksFromHighRiskMembers } from "@/lib/taskGenerator";
import { Task, Member } from "@/types";
import { formatTaskActionForDisplay } from "@/lib/taskActionDisplayLabels";

function getStatusColor(status: string): string {
  switch (status) {
    case "pending":
      return "text-yellow-700 bg-yellow-400/10 border-yellow-400/20";
    case "in progress":
      return "text-blue-700 bg-blue-400/10 border-blue-400/20";
    case "done":
      return "text-green-700 bg-green-400/10 border-green-400/20";
    default:
      return "text-slate-600 bg-slate-100 border-slate-200";
  }
}

function getPriorityColor(priority: "low" | "medium" | "high" | undefined): string {
  switch (priority) {
    case "high":
      return "text-red-600 bg-red-400/10 border-red-400/20";
    case "medium":
      return "text-orange-700 bg-orange-400/10 border-orange-400/20";
    case "low":
      return "text-slate-600 bg-slate-100 border-slate-200";
    default:
      return "text-slate-600 bg-slate-100 border-slate-200";
  }
}

function getStatusLabel(status: Task["status"]): string {
  if (status === "pending") return "未対応";
  if (status === "in progress") return "対応中";
  return "完了";
}

function toTwoLineText(text: string, max = 64): string {
  if (text.length <= max) return text;
  return `${text.slice(0, max)}...`;
}

function mergeServerTasks(fetchedTasks: Task[], members: Member[]): Task[] {
  const autoGeneratedTasks = generateTasksFromHighRiskMembers(members);
  const existingTaskIds = new Set(fetchedTasks.map((t) => t.memberId));
  const newAutoTasks = autoGeneratedTasks.filter(
    (task) => !existingTaskIds.has(task.memberId)
  );
  return [...fetchedTasks, ...newAutoTasks];
}

function buildStatuses(allTasks: Task[]): Record<string, Task["status"]> {
  const initial: Record<string, Task["status"]> = {};
  allTasks.forEach((task) => {
    initial[task.id] = task.status;
  });
  return initial;
}

type Props = {
  initialTasks: Task[];
  initialMembers: Member[];
};

export default function TasksClient({ initialTasks, initialMembers }: Props) {
  const [tasks] = useState<Task[]>(() => mergeServerTasks(initialTasks, initialMembers));
  const [taskStatuses, setTaskStatuses] = useState<Record<string, Task["status"]>>(() =>
    buildStatuses(mergeServerTasks(initialTasks, initialMembers))
  );
  const [isMobile, setIsMobile] = useState(false);

  console.log("[render-check] app/tasks/TasksClient.tsx rendered");

  const handleStartTask = (taskId: string) => {
    setTaskStatuses((prev) => ({
      ...prev,
      [taskId]: "in progress",
    }));
  };

  const handleMarkAsDone = (taskId: string) => {
    setTaskStatuses((prev) => ({
      ...prev,
      [taskId]: "done",
    }));
  };

  const currentTasks = tasks.map((task) => ({
    ...task,
    status: taskStatuses[task.id] || task.status,
  }));

  useEffect(() => {
    const media = window.matchMedia("(max-width: 767px)");
    const sync = () => setIsMobile(media.matches);
    sync();
    media.addEventListener("change", sync);
    return () => media.removeEventListener("change", sync);
  }, []);

  if (tasks.length === 0) {
    return (
      <div className="container mx-auto px-4 py-8 max-w-7xl">
        <div className="mb-6">
          <DashboardBackLink className="text-blue-700 hover:text-blue-800 hover:underline text-sm">
            ← ダッシュボードに戻る
          </DashboardBackLink>
        </div>
        <h1 className="text-4xl font-bold mb-8">介入タスク</h1>
        <div className="bg-white border border-slate-200 shadow-sm rounded-lg p-8 text-center">
          <p className="text-slate-600">表示するタスクがありません</p>
        </div>
      </div>
    );
  }

  const pendingCount = currentTasks.filter((task) => task.status === "pending").length;
  const inProgressCount = currentTasks.filter((task) => task.status === "in progress").length;
  const doneCount = currentTasks.filter((task) => task.status === "done").length;

  return (
    <div className="container mx-auto px-4 py-8 max-w-7xl">
      <div className="mb-6">
        <DashboardBackLink className="text-blue-700 hover:text-blue-800 hover:underline text-sm">
          ← ダッシュボードに戻る
        </DashboardBackLink>
      </div>
      <h1 className="text-2xl md:text-4xl font-bold mb-4 md:mb-8">タスク一覧</h1>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        <div className="bg-white border border-slate-200 shadow-sm rounded-lg p-6 hover:border-slate-200 transition-colors">
          <h2 className="text-slate-600 text-sm font-medium mb-2">未対応タスク</h2>
          <p className="text-3xl font-bold text-yellow-700">{pendingCount}</p>
        </div>

        <div className="bg-white border border-slate-200 shadow-sm rounded-lg p-6 hover:border-slate-200 transition-colors">
          <h2 className="text-slate-600 text-sm font-medium mb-2">対応中タスク</h2>
          <p className="text-3xl font-bold text-blue-700">{inProgressCount}</p>
        </div>

        <div className="bg-white border border-slate-200 shadow-sm rounded-lg p-6 hover:border-slate-200 transition-colors">
          <h2 className="text-slate-600 text-sm font-medium mb-2">完了タスク</h2>
          <p className="text-3xl font-bold text-green-700">{doneCount}</p>
        </div>
      </div>

      {isMobile ? (
      <div className="space-y-1.5">
        {currentTasks.map((task) => (
          <div
            key={task.id}
            className="rounded-md border border-slate-200 bg-white px-2.5 py-2"
          >
            <div className="flex items-start justify-between gap-3">
              <p className="text-sm font-semibold text-slate-900 leading-5 [word-break:normal] break-normal whitespace-normal">
                {task.memberName}
              </p>
            </div>

            <p className="mt-1 text-[11px] leading-4 text-slate-800">
              <span className="text-slate-500">アクション：</span>
              <span className="line-clamp-2 break-words">
                {toTwoLineText(formatTaskActionForDisplay(task.action), 48)}
              </span>
            </p>

            <div className="mt-1 text-[11px] leading-4">
              <p className="text-slate-800">
                <span className="text-slate-500">優先度：</span>
                {task.priority ? (
                  <span
                    className={`inline-flex items-center rounded border px-2 py-0.5 text-xs font-medium ${getPriorityColor(
                      task.priority
                    )}`}
                  >
                    {task.priority === "high" ? "高" : task.priority === "medium" ? "中" : "低"}
                  </span>
                ) : (
                  <span className="text-slate-600 text-xs">-</span>
                )}
              </p>
            </div>

            <div className="mt-1.5 flex flex-wrap gap-1.5">
              {task.status === "pending" && (
                <button
                  type="button"
                  onClick={() => handleStartTask(task.id)}
                  className="rounded px-2 py-1 text-[10px] bg-blue-500/20 text-blue-700 border border-blue-500/30 hover:bg-blue-500/30 transition-colors"
                >
                  タスク開始
                </button>
              )}
              {task.status === "in progress" && (
                <button
                  type="button"
                  onClick={() => handleMarkAsDone(task.id)}
                  className="rounded px-2 py-1 text-[10px] bg-green-500/20 text-green-700 border border-green-500/30 hover:bg-green-500/30 transition-colors"
                >
                  完了にする
                </button>
              )}
              {task.status === "done" && (
                <span className="px-1 py-1 text-[10px] text-slate-500">完了済み</span>
              )}
            </div>
          </div>
        ))}
      </div>
      ) : (
      <div className="bg-white border border-slate-200 shadow-sm rounded-lg overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-slate-100 border-b border-slate-200">
              <tr>
                <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                  会員
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                  アクション
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                  優先度
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                  ステータス
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                  担当トレーナー
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                  期限
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                  操作
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200">
              {currentTasks.map((task) => (
                <tr
                  key={task.id}
                  className="hover:bg-slate-100/80 transition-colors"
                >
                  <td className="px-6 py-4 text-slate-700 font-medium">
                    <div className="flex items-center gap-2">
                      {task.memberName}
                      {task.isAutoGenerated && (
                        <span className="text-xs px-2 py-0.5 rounded bg-blue-500/20 text-blue-700 border border-blue-500/30">
                          自動生成
                        </span>
                      )}
                    </div>
                  </td>
                  <td className="px-6 py-4 text-slate-700">
                    {formatTaskActionForDisplay(task.action)}
                  </td>
                  <td className="px-6 py-4">
                    {task.priority ? (
                      <span
                        className={`inline-flex items-center px-2 py-1 rounded text-xs font-medium border ${getPriorityColor(
                          task.priority
                        )}`}
                      >
                        {task.priority === "high" ? "高" : task.priority === "medium" ? "中" : "低"}
                      </span>
                    ) : (
                      <span className="text-slate-500 text-xs">-</span>
                    )}
                  </td>
                  <td className="px-6 py-4">
                    <span
                      className={`inline-flex items-center px-3 py-1 rounded-full text-xs font-medium border ${getStatusColor(
                        task.status
                      )}`}
                    >
                      {getStatusLabel(task.status)}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-slate-700">
                    {task.assignedTrainer}
                  </td>
                  <td className="px-6 py-4 text-slate-700">{task.dueDate}</td>
                  <td className="px-6 py-4">
                    <div className="flex gap-2">
                      {task.status === "pending" && (
                        <button
                          type="button"
                          onClick={() => handleStartTask(task.id)}
                          className="px-3 py-1.5 text-xs bg-blue-500/20 text-blue-700 border border-blue-500/30 rounded hover:bg-blue-500/30 transition-colors"
                        >
                          タスク開始
                        </button>
                      )}
                      {task.status === "in progress" && (
                        <button
                          type="button"
                          onClick={() => handleMarkAsDone(task.id)}
                          className="px-3 py-1.5 text-xs bg-green-500/20 text-green-700 border border-green-500/30 rounded hover:bg-green-500/30 transition-colors"
                        >
                          完了にする
                        </button>
                      )}
                      {task.status === "done" && (
                        <span className="px-3 py-1.5 text-xs text-slate-500">
                          完了済み
                        </span>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
      )}
    </div>
  );
}
