"use client";

import { useState, type ReactNode } from "react";
import { DashboardBackLink } from "@/components/navigation/DashboardBackLink";
import { ExpandableListItem } from "@/components/ui/ExpandableListItem";
import { generateTasksFromHighRiskMembers } from "@/lib/taskGenerator";
import { getInterventionSuggestion } from "@/lib/interventionSuggestion";
import { getRiskReasons } from "@/lib/riskScore";
import { Task, Member } from "@/types";
import { formatTaskActionForDisplay } from "@/lib/taskActionDisplayLabels";

function getStatusColor(status: string): string {
  switch (status) {
    case "pending":
      return "text-yellow-700 bg-yellow-400/10 border-yellow-400/20";
    case "in progress":
      return "text-blue-700 bg-blue-400/10 border-blue-400/20";
    case "done":
      return "text-green-700 bg-green-400/10 border-green-400/20";
    default:
      return "text-slate-600 bg-slate-100 border-slate-200";
  }
}

function getPriorityColor(priority: "low" | "medium" | "high" | undefined): string {
  switch (priority) {
    case "high":
      return "text-red-600 bg-red-400/10 border-red-400/20";
    case "medium":
      return "text-orange-700 bg-orange-400/10 border-orange-400/20";
    case "low":
      return "text-slate-600 bg-slate-100 border-slate-200";
    default:
      return "text-slate-600 bg-slate-100 border-slate-200";
  }
}

function getStatusLabel(status: Task["status"]): string {
  if (status === "pending") return "未対応";
  if (status === "in progress") return "対応中";
  return "完了";
}

function getMemberRiskLevel(member: Member): "high" | "medium" | "low" {
  const score = member.riskScore ?? 0;
  if (score >= 80) return "high";
  if (score >= 50) return "medium";
  return "low";
}

function getRiskLevelClass(level: "high" | "medium" | "low"): string {
  if (level === "high") return "text-red-600 bg-red-400/10 border-red-400/20";
  if (level === "medium") return "text-orange-700 bg-orange-400/10 border-orange-400/20";
  return "text-green-700 bg-green-400/10 border-green-400/20";
}

function getRiskLevelLabel(level: "high" | "medium" | "low"): string {
  if (level === "high") return "リスク：高";
  if (level === "medium") return "リスク：中";
  return "リスク：低";
}

function toShortText(text: string, max = 64): string {
  if (text.length <= max) return text;
  return `${text.slice(0, max)}…`;
}

function DetailField({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div className="py-3 border-b border-slate-100 last:border-b-0">
      <div className="text-[11px] font-semibold uppercase tracking-wide text-slate-500 mb-1">
        {label}
      </div>
      <div className="text-sm text-slate-900 leading-relaxed">{children}</div>
    </div>
  );
}

function taskCreationReason(task: Task, member: Member | undefined): string {
  if (task.isAutoGenerated) {
    if (member) {
      const suggestion = getInterventionSuggestion(member);
      const p =
        suggestion.priority === "high" ? "高" : suggestion.priority === "medium" ? "中" : "低";
      return `リスク評価・介入提案（優先度：${p}）に基づき自動生成されています。`;
    }
    return "システムにより自動生成されたタスクです。";
  }
  return "手動で登録されたタスクです。";
}

type TaskExpandableRowProps = {
  task: Task;
  member: Member | undefined;
  expanded: boolean;
  onToggleExpand: () => void;
  onStart: () => void;
  onDone: () => void;
};

function TaskExpandableRow({
  task,
  member,
  expanded,
  onToggleExpand,
  onStart,
  onDone,
}: TaskExpandableRowProps) {
  const displayAction = formatTaskActionForDisplay(task.action);
  const riskLevel = member ? getMemberRiskLevel(member) : null;
  const riskReasons = member ? getRiskReasons(member) : [];
  const suggestion = member ? getInterventionSuggestion(member) : null;

  return (
    <ExpandableListItem
      expanded={expanded}
      onToggle={onToggleExpand}
      summary={
        <>
          {/* 会員名 + バッジ */}
          <div className="flex items-center gap-1.5 flex-wrap">
            <p className="text-sm font-semibold text-slate-900 leading-snug">
              {task.memberName}
            </p>
            {task.isAutoGenerated && (
              <span className="shrink-0 text-[10px] px-1.5 py-0.5 rounded bg-blue-500/15 text-blue-800 border border-blue-500/25">
                自動
              </span>
            )}
            {riskLevel && (
              <span
                className={`shrink-0 inline-flex items-center rounded border px-1.5 py-0.5 text-[10px] font-medium ${getRiskLevelClass(riskLevel)}`}
              >
                {getRiskLevelLabel(riskLevel)}
              </span>
            )}
            {task.priority && (
              <span
                className={`shrink-0 inline-flex items-center rounded border px-1.5 py-0.5 text-[10px] font-medium ${getPriorityColor(task.priority)}`}
              >
                {task.priority === "high"
                  ? "優先度：高"
                  : task.priority === "medium"
                    ? "優先度：中"
                    : "優先度：低"}
              </span>
            )}
          </div>

          {/* タスク内容（概要） */}
          <p className="mt-1.5 text-xs text-slate-700 leading-snug line-clamp-1">
            {toShortText(displayAction, 60)}
          </p>

          {/* 期限 + ステータス */}
          <div className="mt-1.5 flex items-center gap-2.5 flex-wrap">
            {task.dueDate && (
              <span className="text-[11px] text-slate-500">期限：{task.dueDate}</span>
            )}
            <span
              className={`inline-flex items-center rounded-full border px-2 py-0.5 text-[10px] font-medium ${getStatusColor(task.status)}`}
            >
              {getStatusLabel(task.status)}
            </span>
          </div>
        </>
      }
    >
      {/* 展開パネル */}
      <div className="mb-3 flex justify-end">
        <button
          type="button"
          onClick={onToggleExpand}
          className="text-sm font-medium text-blue-700 hover:text-blue-800 py-1.5 px-2 -mr-2 rounded-md active:bg-blue-500/10"
        >
          閉じる
        </button>
      </div>

      <DetailField label="タスク内容（全文）">{displayAction}</DetailField>

      {suggestion && (
        <DetailField label="推奨アクション">{suggestion.action}</DetailField>
      )}

      <DetailField label="作成理由">{taskCreationReason(task, member)}</DetailField>

      <DetailField label="会員メモ">
        {member?.notes?.trim() ? member.notes : "会員メモは登録されていません。"}
      </DetailField>

      {riskReasons.length > 0 && (
        <DetailField label="リスク要因">
          <ul className="space-y-1">
            {riskReasons.map((reason, i) => (
              <li key={i} className="flex gap-1.5">
                <span className="text-slate-400">・</span>
                <span>{reason}</span>
              </li>
            ))}
          </ul>
        </DetailField>
      )}

      <DetailField label="担当トレーナー">{task.assignedTrainer || "—"}</DetailField>

      <div className="mt-4 flex flex-wrap gap-2">
        {task.status === "pending" && (
          <button
            type="button"
            onClick={onStart}
            className="rounded-lg px-4 py-2.5 text-sm font-medium bg-blue-600 text-white hover:bg-blue-700 active:scale-[0.98] transition-transform min-h-11"
          >
            対応開始
          </button>
        )}
        {task.status === "in progress" && (
          <button
            type="button"
            onClick={onDone}
            className="rounded-lg px-4 py-2.5 text-sm font-medium bg-green-600 text-white hover:bg-green-700 active:scale-[0.98] transition-transform min-h-11"
          >
            完了にする
          </button>
        )}
        {task.status === "done" && (
          <p className="text-sm text-slate-500 py-2">完了済み</p>
        )}
      </div>
    </ExpandableListItem>
  );
}

function mergeServerTasks(fetchedTasks: Task[], members: Member[]): Task[] {
  const autoGeneratedTasks = generateTasksFromHighRiskMembers(members);
  const existingTaskIds = new Set(fetchedTasks.map((t) => t.memberId));
  const newAutoTasks = autoGeneratedTasks.filter(
    (task) => !existingTaskIds.has(task.memberId)
  );
  return [...fetchedTasks, ...newAutoTasks];
}

function buildStatuses(allTasks: Task[]): Record<string, Task["status"]> {
  const initial: Record<string, Task["status"]> = {};
  allTasks.forEach((task) => {
    initial[task.id] = task.status;
  });
  return initial;
}

type Props = {
  initialTasks: Task[];
  initialMembers: Member[];
};

export default function TasksClient({ initialTasks, initialMembers }: Props) {
  const [tasks] = useState<Task[]>(() => mergeServerTasks(initialTasks, initialMembers));
  const [taskStatuses, setTaskStatuses] = useState<Record<string, Task["status"]>>(() =>
    buildStatuses(mergeServerTasks(initialTasks, initialMembers))
  );
  const [openGroups, setOpenGroups] = useState<Set<string>>(new Set());
  const [expandedTaskId, setExpandedTaskId] = useState<string | null>(null);

  const toggleGroup = (groupKey: string, taskIds: string[]) => {
    const isCurrentlyOpen = openGroups.has(groupKey);
    setOpenGroups((prev) => {
      const next = new Set(prev);
      if (isCurrentlyOpen) next.delete(groupKey);
      else next.add(groupKey);
      return next;
    });
    // グループを閉じるとき、そのグループ内で開いていた詳細も閉じる
    if (isCurrentlyOpen && expandedTaskId !== null && taskIds.includes(expandedTaskId)) {
      setExpandedTaskId(null);
    }
  };

  const handleStartTask = (taskId: string) => {
    setTaskStatuses((prev) => ({ ...prev, [taskId]: "in progress" }));
  };

  const handleMarkAsDone = (taskId: string) => {
    setTaskStatuses((prev) => ({ ...prev, [taskId]: "done" }));
  };

  const currentTasks = tasks.map((task) => ({
    ...task,
    status: taskStatuses[task.id] || task.status,
  }));

  const toggleTask = (taskId: string) => {
    setExpandedTaskId((prev) => (prev === taskId ? null : taskId));
  };

  if (tasks.length === 0) {
    return (
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-8 max-w-7xl">
        <div className="mb-6">
          <DashboardBackLink className="text-blue-700 hover:text-blue-800 hover:underline text-sm">
            ← ダッシュボードに戻る
          </DashboardBackLink>
        </div>
        <h1 className="text-2xl font-bold text-slate-900 mb-8">介入タスク</h1>
        <div className="rounded-xl border border-slate-200 bg-white shadow-sm p-8 text-center">
          <p className="text-slate-500 text-sm">表示するタスクがありません</p>
        </div>
      </div>
    );
  }

  const pendingTasks = currentTasks.filter((t) => t.status === "pending");
  const inProgressTasks = currentTasks.filter((t) => t.status === "in progress");
  const doneTasks = currentTasks.filter((t) => t.status === "done");

  const groups = [
    {
      key: "pending",
      title: "未対応タスク",
      tasks: pendingTasks,
      accentClass: "text-yellow-700",
      borderClass: "border-l-yellow-500",
      countClass: "text-yellow-700",
    },
    {
      key: "inProgress",
      title: "対応中タスク",
      tasks: inProgressTasks,
      accentClass: "text-blue-700",
      borderClass: "border-l-blue-500",
      countClass: "text-blue-700",
    },
    {
      key: "done",
      title: "完了タスク",
      tasks: doneTasks,
      accentClass: "text-green-700",
      borderClass: "border-l-green-500",
      countClass: "text-green-700",
    },
  ];

  return (
    <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-8 max-w-7xl">
      <div className="mb-6">
        <DashboardBackLink className="text-blue-700 hover:text-blue-800 hover:underline text-sm">
          ← ダッシュボードに戻る
        </DashboardBackLink>
      </div>

      <h1 className="text-2xl font-bold text-slate-900 mb-1">介入タスク</h1>
      <p className="text-slate-500 text-sm mb-8">ステータスをクリックして一覧を開き、タスクをクリックすると詳細が展開されます</p>

      {/* 2段アコーディオン */}
      <div className="space-y-3">
        {groups.map((group) => {
          const isOpen = openGroups.has(group.key);
          const taskIds = group.tasks.map((t) => t.id);
          return (
            <div
              key={group.key}
              className={`rounded-xl border border-slate-200 bg-white shadow-sm overflow-hidden border-l-4 ${group.borderClass}`}
            >
              {/* ステータス見出し（クリックで開閉） */}
              <button
                type="button"
                onClick={() => toggleGroup(group.key, taskIds)}
                aria-expanded={isOpen}
                className="w-full flex items-center justify-between gap-3 px-5 py-4 min-h-[3.5rem] bg-slate-100/90 hover:bg-slate-100 active:bg-slate-200/90 transition-colors text-left focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500/45 focus-visible:ring-inset"
              >
                <div className="flex items-center gap-2 min-w-0">
                  <span className={`text-[15px] font-bold leading-snug ${group.accentClass}`}>
                    {group.title}
                  </span>
                  <span className="text-sm text-slate-500 shrink-0">
                    （{group.tasks.length}件）
                  </span>
                </div>
                <span className="shrink-0 text-slate-400 text-sm w-6 text-center" aria-hidden>
                  {isOpen ? "▲" : "▼"}
                </span>
              </button>

              {/* タスク一覧（グループが開いているとき） */}
              {isOpen && (
                <div className="border-t border-slate-200 bg-slate-50 px-3 py-3 space-y-2">
                  {group.tasks.length === 0 ? (
                    <p className="text-sm text-slate-400 text-center py-4">
                      該当するタスクはありません
                    </p>
                  ) : (
                    group.tasks.map((task) => {
                      const member = initialMembers.find((m) => m.id === task.memberId);
                      return (
                        <TaskExpandableRow
                          key={task.id}
                          task={task}
                          member={member}
                          expanded={expandedTaskId === task.id}
                          onToggleExpand={() => toggleTask(task.id)}
                          onStart={() => handleStartTask(task.id)}
                          onDone={() => handleMarkAsDone(task.id)}
                        />
                      );
                    })
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
