"use client";

import { useEffect, useState, type ReactNode } from "react";
import { DashboardBackLink } from "@/components/navigation/DashboardBackLink";
import { ExpandableListItem } from "@/components/ui/ExpandableListItem";
import { generateTasksFromHighRiskMembers } from "@/lib/taskGenerator";
import { getInterventionSuggestion } from "@/lib/interventionSuggestion";
import { Task, Member } from "@/types";
import { formatTaskActionForDisplay } from "@/lib/taskActionDisplayLabels";

function getStatusColor(status: string): string {
  switch (status) {
    case "pending":
      return "text-yellow-700 bg-yellow-400/10 border-yellow-400/20";
    case "in progress":
      return "text-blue-700 bg-blue-400/10 border-blue-400/20";
    case "done":
      return "text-green-700 bg-green-400/10 border-green-400/20";
    default:
      return "text-slate-600 bg-slate-100 border-slate-200";
  }
}

function getPriorityColor(priority: "low" | "medium" | "high" | undefined): string {
  switch (priority) {
    case "high":
      return "text-red-600 bg-red-400/10 border-red-400/20";
    case "medium":
      return "text-orange-700 bg-orange-400/10 border-orange-400/20";
    case "low":
      return "text-slate-600 bg-slate-100 border-slate-200";
    default:
      return "text-slate-600 bg-slate-100 border-slate-200";
  }
}

function getStatusLabel(status: Task["status"]): string {
  if (status === "pending") return "未対応";
  if (status === "in progress") return "対応中";
  return "完了";
}

function toTwoLineText(text: string, max = 64): string {
  if (text.length <= max) return text;
  return `${text.slice(0, max)}...`;
}

function DetailField({
  label,
  children,
}: {
  label: string;
  children: ReactNode;
}) {
  return (
    <div className="py-3.5 border-b border-slate-100 last:border-b-0">
      <div className="text-xs font-semibold uppercase tracking-wide text-slate-500 mb-1.5">
        {label}
      </div>
      <div className="text-sm text-slate-900 leading-relaxed">{children}</div>
    </div>
  );
}

type MobileTaskExpandableRowProps = {
  task: Task;
  member: Member | undefined;
  expanded: boolean;
  onToggleExpand: () => void;
  onStart: () => void;
  onDone: () => void;
};

function MobileTaskExpandableRow({
  task,
  member,
  expanded,
  onToggleExpand,
  onStart,
  onDone,
}: MobileTaskExpandableRowProps) {
  const displayAction = formatTaskActionForDisplay(task.action);

  return (
    <ExpandableListItem
      expanded={expanded}
      onToggle={onToggleExpand}
      summary={
        <>
          <div className="flex items-center gap-2 flex-wrap">
            <p className="text-sm font-semibold text-slate-900 leading-snug">
              {task.memberName}
            </p>
            {task.isAutoGenerated && (
              <span className="shrink-0 text-[10px] px-1.5 py-0.5 rounded bg-blue-500/15 text-blue-800 border border-blue-500/25">
                自動
              </span>
            )}
          </div>
          <p className="mt-2 text-xs leading-relaxed text-slate-800">
            <span className="text-slate-500 font-medium">アクション</span>
            <span className="line-clamp-2 break-words block mt-1">
              {toTwoLineText(displayAction, 56)}
            </span>
          </p>
          <div className="mt-2.5">
            {task.priority ? (
              <span
                className={`inline-flex items-center rounded border px-2 py-1 text-xs font-medium ${getPriorityColor(
                  task.priority
                )}`}
              >
                {task.priority === "high"
                  ? "優先度：高"
                  : task.priority === "medium"
                    ? "優先度：中"
                    : "優先度：低"}
              </span>
            ) : (
              <span className="text-xs text-slate-500">優先度：—</span>
            )}
          </div>
        </>
      }
    >
      <div className="mb-3 flex justify-end">
        <button
          type="button"
          onClick={onToggleExpand}
          className="text-sm font-medium text-blue-700 hover:text-blue-800 py-1.5 px-2 -mr-2 rounded-md active:bg-blue-500/10"
        >
          閉じる
        </button>
      </div>

      <DetailField label="アクション（全文）">{displayAction}</DetailField>
      <DetailField label="ステータス">
        <span
          className={`inline-flex items-center rounded-full border px-3 py-1 text-xs font-medium ${getStatusColor(
            task.status
          )}`}
        >
          {getStatusLabel(task.status)}
        </span>
      </DetailField>
      <DetailField label="担当トレーナー">
        {task.assignedTrainer || "—"}
      </DetailField>
      <DetailField label="期限">{task.dueDate || "—"}</DetailField>
      <DetailField label="対象店舗">
        {member?.storeName ||
          (task.storeId ? `店舗ID: ${task.storeId}` : "—")}
      </DetailField>
      <DetailField label="メモ（会員）">
        {member?.notes?.trim()
          ? member.notes
          : "会員メモは登録されていません。"}
      </DetailField>
      <DetailField label="作成理由">
        {taskCreationReason(task, member)}
      </DetailField>
      <DetailField label="対応履歴">
        <span className="text-slate-500">
          タスク単位の対応履歴は未連携です。
        </span>
      </DetailField>

      <div className="mt-4 flex flex-wrap gap-2">
        {task.status === "pending" && (
          <button
            type="button"
            onClick={onStart}
            className="rounded-lg px-4 py-2.5 text-sm font-medium bg-blue-600 text-white hover:bg-blue-700 active:scale-[0.98] transition-transform min-h-11"
          >
            対応開始
          </button>
        )}
        {task.status === "in progress" && (
          <button
            type="button"
            onClick={onDone}
            className="rounded-lg px-4 py-2.5 text-sm font-medium bg-green-600 text-white hover:bg-green-700 active:scale-[0.98] transition-transform min-h-11"
          >
            完了にする
          </button>
        )}
        {task.status === "done" && (
          <p className="text-sm text-slate-500 py-2">完了済み</p>
        )}
      </div>
    </ExpandableListItem>
  );
}

function taskCreationReason(task: Task, member: Member | undefined): string {
  if (task.isAutoGenerated) {
    if (member) {
      const suggestion = getInterventionSuggestion(member);
      const p =
        suggestion.priority === "high"
          ? "高"
          : suggestion.priority === "medium"
            ? "中"
            : "低";
      return `リスク評価・介入提案（優先度：${p}）に基づき自動生成されています。`;
    }
    return "システムにより自動生成されたタスクです。";
  }
  return "手動で登録されたタスクです。";
}

function mergeServerTasks(fetchedTasks: Task[], members: Member[]): Task[] {
  const autoGeneratedTasks = generateTasksFromHighRiskMembers(members);
  const existingTaskIds = new Set(fetchedTasks.map((t) => t.memberId));
  const newAutoTasks = autoGeneratedTasks.filter(
    (task) => !existingTaskIds.has(task.memberId)
  );
  return [...fetchedTasks, ...newAutoTasks];
}

function buildStatuses(allTasks: Task[]): Record<string, Task["status"]> {
  const initial: Record<string, Task["status"]> = {};
  allTasks.forEach((task) => {
    initial[task.id] = task.status;
  });
  return initial;
}

type MobileStatusGroup = "pending" | "inProgress" | "done";

type MobileGroupDef = {
  key: MobileStatusGroup;
  title: string;
  tasks: Task[];
  count: number;
  leftBarClass: string;
  countAccentClass: string;
};

type Props = {
  initialTasks: Task[];
  initialMembers: Member[];
};

export default function TasksClient({ initialTasks, initialMembers }: Props) {
  const [tasks] = useState<Task[]>(() => mergeServerTasks(initialTasks, initialMembers));
  const [taskStatuses, setTaskStatuses] = useState<Record<string, Task["status"]>>(() =>
    buildStatuses(mergeServerTasks(initialTasks, initialMembers))
  );
  const [isMobile, setIsMobile] = useState(false);
  const [expandedTaskIds, setExpandedTaskIds] = useState<Set<string>>(
    () => new Set()
  );
  const [openGroups, setOpenGroups] = useState<Set<MobileStatusGroup>>(
    () => new Set()
  );

  console.log("[render-check] app/tasks/TasksClient.tsx rendered");

  const handleStartTask = (taskId: string) => {
    setTaskStatuses((prev) => ({
      ...prev,
      [taskId]: "in progress",
    }));
  };

  const handleMarkAsDone = (taskId: string) => {
    setTaskStatuses((prev) => ({
      ...prev,
      [taskId]: "done",
    }));
  };

  const currentTasks = tasks.map((task) => ({
    ...task,
    status: taskStatuses[task.id] || task.status,
  }));

  const toggleTaskExpanded = (taskId: string) => {
    setExpandedTaskIds((prev) => {
      const next = new Set(prev);
      if (next.has(taskId)) next.delete(taskId);
      else next.add(taskId);
      return next;
    });
  };

  const toggleGroup = (key: MobileStatusGroup) => {
    setOpenGroups((prev) => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  };

  useEffect(() => {
    const media = window.matchMedia("(max-width: 767px)");
    const sync = () => {
      const mobile = media.matches;
      setIsMobile(mobile);
      if (!mobile) {
        setExpandedTaskIds(new Set());
        setOpenGroups(new Set());
      }
    };
    sync();
    media.addEventListener("change", sync);
    return () => media.removeEventListener("change", sync);
  }, []);

  if (tasks.length === 0) {
    return (
      <div className="container mx-auto px-4 py-8 max-w-7xl">
        <div className="mb-6">
          <DashboardBackLink className="text-blue-700 hover:text-blue-800 hover:underline text-sm">
            ← ダッシュボードに戻る
          </DashboardBackLink>
        </div>
        <h1 className="text-4xl font-bold mb-8">介入タスク</h1>
        <div className="bg-white border border-slate-200 shadow-sm rounded-lg p-8 text-center">
          <p className="text-slate-600">表示するタスクがありません</p>
        </div>
      </div>
    );
  }

  const pendingCount = currentTasks.filter((task) => task.status === "pending").length;
  const inProgressCount = currentTasks.filter((task) => task.status === "in progress").length;
  const doneCount = currentTasks.filter((task) => task.status === "done").length;

  const pendingTasks = currentTasks.filter((task) => task.status === "pending");
  const inProgressTasks = currentTasks.filter(
    (task) => task.status === "in progress"
  );
  const doneTasks = currentTasks.filter((task) => task.status === "done");

  const mobileGroups: MobileGroupDef[] = [
    {
      key: "pending",
      title: "未対応タスク",
      tasks: pendingTasks,
      count: pendingCount,
      leftBarClass: "border-l-yellow-500",
      countAccentClass: "text-yellow-700",
    },
    {
      key: "inProgress",
      title: "対応中タスク",
      tasks: inProgressTasks,
      count: inProgressCount,
      leftBarClass: "border-l-blue-500",
      countAccentClass: "text-blue-700",
    },
    {
      key: "done",
      title: "完了タスク",
      tasks: doneTasks,
      count: doneCount,
      leftBarClass: "border-l-green-500",
      countAccentClass: "text-green-700",
    },
  ];

  return (
    <div className="container mx-auto px-4 py-8 max-w-7xl">
      <div className="mb-6">
        <DashboardBackLink className="text-blue-700 hover:text-blue-800 hover:underline text-sm">
          ← ダッシュボードに戻る
        </DashboardBackLink>
      </div>
      <h1 className="text-2xl md:text-4xl font-bold mb-4 md:mb-8">タスク一覧</h1>

      <div className="hidden md:grid md:grid-cols-3 gap-6 mb-8">
        <div className="bg-white border border-slate-200 shadow-sm rounded-lg p-6 hover:border-slate-200 transition-colors">
          <h2 className="text-slate-600 text-sm font-medium mb-2">未対応タスク</h2>
          <p className="text-3xl font-bold text-yellow-700">{pendingCount}</p>
        </div>

        <div className="bg-white border border-slate-200 shadow-sm rounded-lg p-6 hover:border-slate-200 transition-colors">
          <h2 className="text-slate-600 text-sm font-medium mb-2">対応中タスク</h2>
          <p className="text-3xl font-bold text-blue-700">{inProgressCount}</p>
        </div>

        <div className="bg-white border border-slate-200 shadow-sm rounded-lg p-6 hover:border-slate-200 transition-colors">
          <h2 className="text-slate-600 text-sm font-medium mb-2">完了タスク</h2>
          <p className="text-3xl font-bold text-green-700">{doneCount}</p>
        </div>
      </div>

      {isMobile ? (
        <div className="space-y-3 md:hidden mb-6">
          {mobileGroups.map((group) => {
            const open = openGroups.has(group.key);
            return (
              <div
                key={group.key}
                className={`rounded-lg border border-slate-200 shadow-sm overflow-hidden bg-white border-l-4 ${group.leftBarClass}`}
              >
                <button
                  type="button"
                  onClick={() => toggleGroup(group.key)}
                  className="w-full flex items-center justify-between gap-3 px-4 py-3.5 min-h-[3.25rem] text-left bg-slate-100/90 hover:bg-slate-100 active:bg-slate-200/90 transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500/45 focus-visible:ring-inset"
                  aria-expanded={open}
                >
                  <div className="min-w-0 flex-1">
                    <p className="text-[15px] font-bold text-slate-900 leading-snug">
                      <span className={group.countAccentClass}>{group.title}</span>
                      <span className="text-slate-800">
                        （{group.count}件）
                      </span>
                    </p>
                  </div>
                  <span
                    className="shrink-0 text-slate-500 text-sm font-medium w-7 text-center"
                    aria-hidden
                  >
                    {open ? "▲" : "▼"}
                  </span>
                </button>

                {open ? (
                  <div className="border-t border-slate-200 bg-slate-50 px-3 py-3 space-y-2.5">
                    {group.tasks.length === 0 ? (
                      <p className="text-sm text-slate-500 text-center py-4">
                        該当タスクはありません
                      </p>
                    ) : (
                      group.tasks.map((task) => {
                        const member = initialMembers.find(
                          (m) => m.id === task.memberId
                        );
                        return (
                          <MobileTaskExpandableRow
                            key={task.id}
                            task={task}
                            member={member}
                            expanded={expandedTaskIds.has(task.id)}
                            onToggleExpand={() => toggleTaskExpanded(task.id)}
                            onStart={() => handleStartTask(task.id)}
                            onDone={() => handleMarkAsDone(task.id)}
                          />
                        );
                      })
                    )}
                  </div>
                ) : null}
              </div>
            );
          })}
        </div>
      ) : null}

      {!isMobile ? (
      <div className="bg-white border border-slate-200 shadow-sm rounded-lg overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-slate-100 border-b border-slate-200">
              <tr>
                <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                  会員
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                  アクション
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                  優先度
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                  ステータス
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                  担当トレーナー
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                  期限
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                  操作
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200">
              {currentTasks.map((task) => (
                <tr
                  key={task.id}
                  className="hover:bg-slate-100/80 transition-colors"
                >
                  <td className="px-6 py-4 text-slate-700 font-medium">
                    <div className="flex items-center gap-2">
                      {task.memberName}
                      {task.isAutoGenerated && (
                        <span className="text-xs px-2 py-0.5 rounded bg-blue-500/20 text-blue-700 border border-blue-500/30">
                          自動生成
                        </span>
                      )}
                    </div>
                  </td>
                  <td className="px-6 py-4 text-slate-700">
                    {formatTaskActionForDisplay(task.action)}
                  </td>
                  <td className="px-6 py-4">
                    {task.priority ? (
                      <span
                        className={`inline-flex items-center px-2 py-1 rounded text-xs font-medium border ${getPriorityColor(
                          task.priority
                        )}`}
                      >
                        {task.priority === "high" ? "高" : task.priority === "medium" ? "中" : "低"}
                      </span>
                    ) : (
                      <span className="text-slate-500 text-xs">-</span>
                    )}
                  </td>
                  <td className="px-6 py-4">
                    <span
                      className={`inline-flex items-center px-3 py-1 rounded-full text-xs font-medium border ${getStatusColor(
                        task.status
                      )}`}
                    >
                      {getStatusLabel(task.status)}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-slate-700">
                    {task.assignedTrainer}
                  </td>
                  <td className="px-6 py-4 text-slate-700">{task.dueDate}</td>
                  <td className="px-6 py-4">
                    <div className="flex gap-2">
                      {task.status === "pending" && (
                        <button
                          type="button"
                          onClick={() => handleStartTask(task.id)}
                          className="px-3 py-1.5 text-xs bg-blue-500/20 text-blue-700 border border-blue-500/30 rounded hover:bg-blue-500/30 transition-colors"
                        >
                          タスク開始
                        </button>
                      )}
                      {task.status === "in progress" && (
                        <button
                          type="button"
                          onClick={() => handleMarkAsDone(task.id)}
                          className="px-3 py-1.5 text-xs bg-green-500/20 text-green-700 border border-green-500/30 rounded hover:bg-green-500/30 transition-colors"
                        >
                          完了にする
                        </button>
                      )}
                      {task.status === "done" && (
                        <span className="px-3 py-1.5 text-xs text-slate-500">
                          完了済み
                        </span>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
      ) : null}
    </div>
  );
}
