/**
 * ユーザーロール定義
 * 権限別ダッシュボードで使用
 */
export type Role = "admin" | "owner" | "manager" | "trainer";

/**
 * Supabaseデータベースの型定義（スネークケース）
 * これらの型はSupabaseから取得した生データに対応
 */

/**
 * Supabase members テーブルの型
 */
export interface SupabaseMember {
  id: string;
  name: string;
  plan: string;
  join_date: string;
  last_visit_date: string;
  visit_interval: string;
  has_cancellation_history?: boolean;
  monthly_revenue?: number;
  store_id?: string;
  store_name: string;
  assigned_trainer?: string;
  notes?: string;
  created_at?: string;
  updated_at?: string;
}

/**
 * Supabase visits テーブルの型
 */
export interface SupabaseVisit {
  id: string;
  member_id: string;
  visit_date: string;
  created_at?: string;
}

/**
 * Supabase interventions テーブルの型
 */
export interface SupabaseIntervention {
  id: string;
  member_id: string;
  type: string;
  title: string;
  action?: string;
  priority: "low" | "medium" | "high";
  status: "pending" | "in progress" | "completed";
  trainer?: string;
  created_at?: string;
  updated_at?: string;
}

/**
 * Supabase tasks テーブルの型
 */
export interface SupabaseTask {
  id: string;
  member_id: string;
  member_name: string;
  action: string;
  status: "pending" | "in progress" | "done";
  assigned_trainer: string;
  due_date: string;
  store_id?: string;
  priority?: "low" | "medium" | "high";
  is_auto_generated?: boolean;
  created_at?: string;
  updated_at?: string;
}

/**
 * アプリケーション層の型定義（キャメルケース）
 * これらの型はアプリケーション全体で使用
 */

/**
 * 会員情報
 * Supabase接続時は members テーブルに対応
 * 計算フィールド（riskScore, interventionStatus等）はアプリケーション側で計算
 */
export interface Member {
  id: string;
  name: string;
  plan: string;
  storeId?: string;
  storeName: string;
  joinDate: string;
  lastVisitDate: string;
  visitInterval: string;
  // 計算フィールド（DBには保存しない）
  riskScore?: number;
  interventionStatus?: string;
  recommendedIntervention?: string;
  // DBフィールド
  monthlyRevenue?: number;
  hasCancellationHistory?: boolean;
  assignedTrainer?: string;
  notes?: string;
  // 拡張フィールド（現在はモックデータのみ、将来別テーブルまたはJSONBで管理）
  // 予約分析用データ
  preferredTimeSlot?: string; // 例: "19:00-20:00"
  bookedTimeSlot?: string; // 実際に予約できた時間帯
  reservationDifficultyLevel?: "easy" | "medium" | "difficult"; // 予約の取りづらさ
  preferredWeekday?: string; // 例: "月", "火", "水", "木", "金", "土", "日"
  preferredHour?: number; // 0-23
  // デュアル移行最適化用データ
  currentPlan?: string; // 現在のプラン（planと同じ値または別途設定）
  recommendedNextPlan?: "トレーニング月8" | "ピラティス月8"; // 推奨移行先
  trainingFitScore?: number; // トレーニング適性スコア（0-100）
  pilatesFitScore?: number; // ピラティス適性スコア（0-100）
  // 価格改定影響モニター用データ
  isPriceRevisionTarget?: boolean; // 価格改定対象かどうか
  priceRevisionBeforeRevenue?: number; // 改定前月額売上
  priceRevisionAfterRevenue?: number; // 改定後月額売上
}

/**
 * 会員作成用入力（アプリケーション層）
 * Supabase接続後もこの形を維持するとCRUDが差し替えやすい
 */
export interface MemberCreateInput {
  name: string;
  plan: string;
  joinDate: string; // YYYY-MM-DD
  storeName: string;
  assignedTrainer?: string;
  notes?: string;
  // CSVインポート用の拡張フィールド（任意）
  lastVisitDate?: string; // YYYY-MM-DD
  visitInterval?: string;
  hasCancellationHistory?: boolean;
  monthlyRevenue?: number;
}

/**
 * 会員更新用入力（部分更新）
 */
export type MemberUpdateInput = Partial<MemberCreateInput> & {
  lastVisitDate?: string; // YYYY-MM-DD
  visitInterval?: string;
  hasCancellationHistory?: boolean;
  monthlyRevenue?: number;
};

/**
 * 訪問履歴
 * Supabase接続時は visits テーブルに対応
 */
export interface Visit {
  id: string;
  memberId: string;
  visitDate: string;
}

/**
 * 介入履歴
 * Supabase接続時は interventions テーブルに対応
 */
export interface Intervention {
  id: string;
  memberId: string;
  type: string;
  title?: string; // Supabaseでは必須だが、既存モックデータとの互換性のためオプショナル
  action?: string;
  priority?: "low" | "medium" | "high"; // 既存モックデータとの互換性のためオプショナル
  status: string; // "pending" | "in progress" | "completed" | "Completed" | "Pending" など
  trainer?: string;
  createdAt: string;
}

/**
 * タスク
 * Supabase接続時は tasks テーブルに対応
 */
export interface Task {
  id: string;
  memberId: string;
  memberName: string;
  action: string;
  status: "pending" | "in progress" | "done";
  assignedTrainer: string;
  dueDate: string;
  storeId?: string;
  priority?: "low" | "medium" | "high";
  isAutoGenerated?: boolean; // 自動生成タスクかどうか
}

export type ContractStatus = "active" | "trial" | "inactive" | "suspended";

export interface Store {
  id: string;
  name: string;
  contractStatus: ContractStatus;
  ownerId?: string | null;
}

export type MembershipRole = "trainer" | "owner" | "hq" | "staff";

export interface UserStoreMembership {
  id: string;
  userId: string;
  storeId: string;
  role: MembershipRole;
  createdAt: string;
}

/**
 * 会話ログ自動タグ（ルールベース抽出）
 */
export type ConversationTagCategory =
  | "生活"
  | "体調"
  | "食事"
  | "心理"
  | "姿勢"
  | "目標";

export interface ConversationTag {
  tag: string;
  category: ConversationTagCategory;
}

export type ChurnReasonCategory =
  | "行動"
  | "継続初期"
  | "生活"
  | "体調"
  | "心理"
  | "食事"
  | "目標";

export interface ChurnReasonTag {
  tag: string;
  confidence: number; // 0-1
  description: string;
  category: ChurnReasonCategory;
  severity: "high" | "medium";
}

export interface ChurnReasonEstimate {
  reasons: ChurnReasonTag[];
  primaryReason?: string;
}

export type NextActionPriority = "high" | "medium" | "low";

export type NextActionType =
  | "会話"
  | "トレーニング"
  | "介入"
  | "行動"
  | "体調"
  | "心理"
  | "目標"
  | "継続";

export interface NextActionItem {
  type: NextActionType;
  title: string;
  description: string;
}

export interface NextActionSuggestion {
  priority: NextActionPriority;
  actions: NextActionItem[];
}

export type TrainerEvaluationLevel =
  | "excellent"
  | "good"
  | "watch"
  | "support_needed";

export interface TrainerEvaluationInsight {
  title: string;
  description: string;
}

export interface TrainerEvaluationResult {
  trainerName: string;
  summaryScore: number;
  level: TrainerEvaluationLevel;
  strengths: TrainerEvaluationInsight[];
  improvementPoints: TrainerEvaluationInsight[];
  actionItems: string[];
  metrics: {
    totalMembers: number;
    highRiskMembers: number;
    estimatedRetentionRate: number;
    highChurn30DaysMembers: number;
    annualRevenueAtRisk: number;
    earlyHighRiskMembers90Days: number;
    sessionRecordCount: number;
    sessionRecordQuality: number;
  };
}

export interface SuccessSessionPattern {
  title: string;
  description: string;
  impactScore: number;
}

export interface HighPerformingSessionTrait {
  trait: string;
  description: string;
}

export interface SuccessSessionAnalysis {
  commonPatterns: SuccessSessionPattern[];
  highPerformingSessionTraits: HighPerformingSessionTrait[];
  recommendedActions: string[];
}

export interface StorePerformanceSummary {
  storeName: string;
  totalMembers: number;
  highRiskMembers: number;
  estimatedRetentionRate: number;
  monthlyRevenue: number;
  expectedLoss30Days: number;
  successScore: number;
  riskScore: number;
}

/** 収益改善AIの推奨アクション1行 */
export interface RevenueImprovementAction {
  title: string;
  impact: string;
}

/** 本部向け改善提案AIの出力 */
export interface HQActionPlan {
  topIssue: string;
  priorityLabel: "high" | "medium" | "low";
  summary: string;
  actions: string[];
  /** 今月優先して対応すべき店舗（最大3） */
  priorityStores: string[];
}

/** 収益改善AIのプラン出力 */
export interface RevenueImprovementPlan {
  topPriority: string;
  expectedImpact: string;
  actions: RevenueImprovementAction[];
  /** 高LTVかつ高リスクの会員数 */
  highImpactMemberCount: number;
  metrics: {
    monthlyRevenue: number;
    avgRiskAdjustedLTV: number;
    expectedLoss30Days: number;
    expectedLoss60Days: number;
    highRiskMembers: number;
    first90HighRiskCount: number;
    reservationRiskCount: number;
  };
}

/**
 * セッション履歴（CSVインポート対応）
 * 会員詳細で直近のセッションを表示する用途
 */
export interface Session {
  id: string;
  memberName: string;
  sessionDate: string; // YYYY-MM-DD
  menuSummary: string;
  conversationSummary: string;
  /**
   * セッション中の会話・生活・モチベ等の自由記述（トレーニング記録とは別管理）
   */
  conversationNotes?: string;
  nextAction: string;
  trainerName: string;
  storeName: string;
  /** 会話要約から自動付与（CSV取り込み時・保存時に補完） */
  tags?: ConversationTag[];
}
