import { Member, Visit, Intervention, Task } from "@/types";

export const members: Member[] = [
  {
    id: "1",
    name: "田中太郎",
    plan: "Premium",
    storeName: "三軒茶屋本店",
    joinDate: "2023-06-15",
    lastVisitDate: "2024-01-15",
    visitInterval: "3 days",
    riskScore: 85,
    interventionStatus: "High Priority",
    recommendedIntervention: "Immediate follow-up consultation required",
    notes: "Member has been showing decreased engagement. Risk score has increased significantly over the past month.",
    monthlyRevenue: 39800,
    preferredTimeSlot: "19:00-20:00",
    bookedTimeSlot: "21:00-22:00",
    reservationDifficultyLevel: "difficult",
    preferredWeekday: "月",
    preferredHour: 19,
    assignedTrainer: "山本トレーナー",
    isPriceRevisionTarget: true,
    priceRevisionBeforeRevenue: 39800,
    priceRevisionAfterRevenue: 43000,
  },
  {
    id: "2",
    name: "佐藤花子",
    plan: "Standard",
    storeName: "人形町店",
    joinDate: "2023-08-20",
    lastVisitDate: "2024-01-20",
    visitInterval: "5 days",
    riskScore: 65,
    interventionStatus: "Monitor",
    recommendedIntervention: "Nutrition plan review",
    notes: "Regular check-ins are going well. Monitor progress closely.",
    monthlyRevenue: 26000,
    preferredTimeSlot: "18:00-19:00",
    bookedTimeSlot: "18:00-19:00",
    reservationDifficultyLevel: "easy",
    preferredWeekday: "火",
    preferredHour: 18,
    assignedTrainer: "佐々木トレーナー",
    isPriceRevisionTarget: true,
    priceRevisionBeforeRevenue: 26000,
    priceRevisionAfterRevenue: 28000,
  },
  {
    id: "3",
    name: "鈴木一郎",
    plan: "Basic",
    storeName: "水天宮前店",
    joinDate: "2023-11-10",
    lastVisitDate: "2024-01-22",
    visitInterval: "2 days",
    riskScore: 35,
    interventionStatus: "Normal",
    recommendedIntervention: "Continue current program",
    notes: "Excellent progress. Member is highly engaged and following the program consistently.",
    monthlyRevenue: 16000,
    preferredTimeSlot: "20:00-21:00",
    bookedTimeSlot: "20:00-21:00",
    reservationDifficultyLevel: "easy",
    preferredWeekday: "水",
    preferredHour: 20,
    assignedTrainer: "山本トレーナー",
    isPriceRevisionTarget: false,
  },
  {
    id: "4",
    name: "山田次郎",
    plan: "Premium",
    storeName: "渋谷店",
    joinDate: "2023-05-05",
    lastVisitDate: "2024-01-10",
    visitInterval: "10 days",
    riskScore: 92,
    interventionStatus: "Urgent",
    recommendedIntervention: "Urgent intervention - schedule emergency consultation",
    notes: "Critical situation. Member has not visited in 10 days. Risk score is extremely high.",
    monthlyRevenue: 39800,
    preferredTimeSlot: "19:00-20:00",
    bookedTimeSlot: undefined,
    reservationDifficultyLevel: "difficult",
    preferredWeekday: "木",
    preferredHour: 19,
    hasCancellationHistory: true,
    assignedTrainer: "佐々木トレーナー",
    isPriceRevisionTarget: true,
    priceRevisionBeforeRevenue: 39800,
    priceRevisionAfterRevenue: 43000,
  },
  {
    id: "5",
    name: "伊藤美咲",
    plan: "Standard",
    storeName: "中野店",
    joinDate: "2023-09-12",
    lastVisitDate: "2024-01-21",
    visitInterval: "4 days",
    riskScore: 45,
    interventionStatus: "Normal",
    recommendedIntervention: "Workout plan adjustment",
    notes: "Good progress overall. Minor adjustments needed to optimize results.",
    monthlyRevenue: 26000,
    preferredTimeSlot: "18:00-19:00",
    bookedTimeSlot: "19:00-20:00",
    reservationDifficultyLevel: "medium",
    preferredWeekday: "金",
    preferredHour: 18,
    assignedTrainer: "山本トレーナー",
    isPriceRevisionTarget: true,
    priceRevisionBeforeRevenue: 26000,
    priceRevisionAfterRevenue: 28000,
  },
  {
    id: "6",
    name: "高橋健太",
    plan: "Premium",
    storeName: "三軒茶屋本店",
    joinDate: "2023-07-01",
    lastVisitDate: "2024-01-23",
    visitInterval: "1 day",
    riskScore: 25,
    interventionStatus: "Normal",
    recommendedIntervention: "Continue excellent progress",
    notes: "Highly motivated member with consistent attendance. Risk score is very low.",
    monthlyRevenue: 33000,
    preferredTimeSlot: "20:00-21:00",
    bookedTimeSlot: "20:00-21:00",
    reservationDifficultyLevel: "easy",
    preferredWeekday: "土",
    preferredHour: 20,
    assignedTrainer: "佐々木トレーナー",
    isPriceRevisionTarget: false,
  },
  {
    id: "13",
    name: "渡辺さくら",
    plan: "デュアル月8",
    currentPlan: "デュアル月8",
    storeName: "人形町店",
    joinDate: "2023-12-01",
    lastVisitDate: "2024-01-20",
    visitInterval: "6 days",
    riskScore: 55,
    interventionStatus: "Monitor",
    recommendedIntervention: "Plan transition consideration",
    notes: "デュアルプランで継続中。移行先の検討が必要。",
    monthlyRevenue: 33000,
    preferredTimeSlot: "18:00-19:00",
    bookedTimeSlot: "18:00-19:00",
    reservationDifficultyLevel: "easy",
    preferredWeekday: "火",
    preferredHour: 18,
  },
  {
    id: "14",
    name: "中島健",
    plan: "デュアル月8",
    currentPlan: "デュアル月8",
    storeName: "渋谷店",
    joinDate: "2023-10-15",
    lastVisitDate: "2024-01-22",
    visitInterval: "2 days",
    riskScore: 30,
    interventionStatus: "Normal",
    recommendedIntervention: "Plan transition consideration",
    notes: "デュアルプランで順調に継続。移行先の提案が可能。",
    monthlyRevenue: 33000,
    preferredTimeSlot: "19:00-20:00",
    bookedTimeSlot: "19:00-20:00",
    reservationDifficultyLevel: "easy",
    preferredWeekday: "水",
    preferredHour: 19,
  },
  {
    id: "15",
    name: "前田由美",
    plan: "デュアル月8",
    currentPlan: "デュアル月8",
    storeName: "中野店",
    joinDate: "2023-11-20",
    lastVisitDate: "2024-01-15",
    visitInterval: "8 days",
    riskScore: 60,
    interventionStatus: "Monitor",
    recommendedIntervention: "Plan transition consideration",
    notes: "デュアルプランで来店間隔が空きがち。移行先の検討が必要。",
    monthlyRevenue: 33000,
    preferredTimeSlot: "17:00-18:00",
    bookedTimeSlot: "17:00-18:00",
    reservationDifficultyLevel: "medium",
    preferredWeekday: "木",
    preferredHour: 17,
    hasCancellationHistory: true,
  },
  {
    id: "16",
    name: "藤原大輔",
    plan: "デュアル月8",
    currentPlan: "デュアル月8",
    storeName: "三軒茶屋本店",
    joinDate: "2024-01-05",
    lastVisitDate: "2024-01-24",
    visitInterval: "3 days",
    riskScore: 40,
    interventionStatus: "Normal",
    recommendedIntervention: "Plan transition consideration",
    notes: "新規入会。デュアルプランで順調に継続中。",
    monthlyRevenue: 33000,
    preferredTimeSlot: "20:00-21:00",
    bookedTimeSlot: "20:00-21:00",
    reservationDifficultyLevel: "easy",
    preferredWeekday: "金",
    preferredHour: 20,
  },
  {
    id: "17",
    name: "村上麻衣",
    plan: "デュアル月8",
    currentPlan: "デュアル月8",
    storeName: "水天宮前店",
    joinDate: "2023-09-10",
    lastVisitDate: "2024-01-18",
    visitInterval: "12 days",
    riskScore: 70,
    interventionStatus: "High Priority",
    recommendedIntervention: "Plan transition consideration",
    notes: "デュアルプランで来店間隔が長くなっている。移行先の検討が急務。",
    monthlyRevenue: 33000,
    preferredTimeSlot: "19:00-20:00",
    bookedTimeSlot: "19:00-20:00",
    reservationDifficultyLevel: "medium",
    preferredWeekday: "土",
    preferredHour: 19,
  },
];

// 訪問履歴データ
export const visits: Visit[] = [
  {
    id: "v1",
    memberId: "1",
    visitDate: "2024-01-15",
  },
  {
    id: "v2",
    memberId: "1",
    visitDate: "2024-01-12",
  },
  {
    id: "v3",
    memberId: "1",
    visitDate: "2024-01-08",
  },
  {
    id: "v4",
    memberId: "2",
    visitDate: "2024-01-20",
  },
  {
    id: "v5",
    memberId: "2",
    visitDate: "2024-01-15",
  },
  {
    id: "v6",
    memberId: "2",
    visitDate: "2024-01-10",
  },
  {
    id: "v7",
    memberId: "3",
    visitDate: "2024-01-22",
  },
  {
    id: "v8",
    memberId: "3",
    visitDate: "2024-01-20",
  },
  {
    id: "v9",
    memberId: "3",
    visitDate: "2024-01-18",
  },
  {
    id: "v10",
    memberId: "4",
    visitDate: "2024-01-10",
  },
  {
    id: "v11",
    memberId: "4",
    visitDate: "2024-01-05",
  },
  {
    id: "v12",
    memberId: "4",
    visitDate: "2023-12-28",
  },
  {
    id: "v13",
    memberId: "5",
    visitDate: "2024-01-21",
  },
  {
    id: "v14",
    memberId: "5",
    visitDate: "2024-01-17",
  },
  {
    id: "v15",
    memberId: "5",
    visitDate: "2024-01-14",
  },
  {
    id: "v16",
    memberId: "6",
    visitDate: "2024-01-23",
  },
  {
    id: "v17",
    memberId: "6",
    visitDate: "2024-01-22",
  },
];

// 介入履歴データ
export const interventions: Intervention[] = [
  {
    id: "i1",
    memberId: "1",
    type: "Follow-up Consultation",
    action: "Conducted phone consultation to discuss progress",
    status: "Completed",
    trainer: "山本トレーナー",
    createdAt: "2024-01-15",
  },
  {
    id: "i2",
    memberId: "1",
    type: "Nutrition Review",
    action: "Reviewed and updated nutrition plan",
    status: "Completed",
    trainer: "山本トレーナー",
    createdAt: "2024-01-08",
  },
  {
    id: "i3",
    memberId: "1",
    type: "Program Adjustment",
    action: "Modified workout program based on feedback",
    status: "Completed",
    trainer: "佐々木トレーナー",
    createdAt: "2023-12-20",
  },
  {
    id: "i4",
    memberId: "2",
    type: "Progress Review",
    action: "Monthly progress check and goal setting",
    status: "Completed",
    trainer: "佐々木トレーナー",
    createdAt: "2024-01-20",
  },
  {
    id: "i5",
    memberId: "2",
    type: "Nutrition Plan Update",
    action: "Updated meal plan for better results",
    status: "Completed",
    trainer: "山本トレーナー",
    createdAt: "2024-01-05",
  },
  {
    id: "i6",
    memberId: "3",
    type: "Monthly Check-in",
    action: "Regular monthly consultation",
    status: "Completed",
    trainer: "山本トレーナー",
    createdAt: "2024-01-18",
  },
  {
    id: "i7",
    memberId: "4",
    type: "Emergency Consultation",
    action: "Urgent consultation due to high risk score",
    status: "Completed",
    trainer: "佐々木トレーナー",
    createdAt: "2024-01-10",
  },
  {
    id: "i8",
    memberId: "4",
    type: "Risk Assessment",
    action: "Comprehensive risk assessment and intervention plan",
    status: "Completed",
    trainer: "山本トレーナー",
    createdAt: "2023-12-28",
  },
  {
    id: "i9",
    memberId: "4",
    type: "Program Review",
    action: "Full program review and adjustment",
    status: "Completed",
    trainer: "佐々木トレーナー",
    createdAt: "2023-12-15",
  },
  {
    id: "i10",
    memberId: "5",
    type: "Plan Adjustment",
    action: "Adjusted workout plan for better engagement",
    status: "Completed",
    trainer: "山本トレーナー",
    createdAt: "2024-01-14",
  },
  {
    id: "i11",
    memberId: "5",
    type: "Progress Review",
    action: "Quarterly progress review session",
    status: "Completed",
    trainer: "佐々木トレーナー",
    createdAt: "2024-01-01",
  },
  {
    id: "i12",
    memberId: "6",
    type: "Initial Assessment",
    action: "Initial consultation and goal setting",
    status: "Completed",
    trainer: "佐々木トレーナー",
    createdAt: "2024-01-22",
  },
];

// タスクデータ
export const tasks: Task[] = [
  {
    id: "t1",
    memberId: "1",
    memberName: "田中太郎",
    action: "Follow-up consultation",
    status: "pending",
    assignedTrainer: "山本トレーナー",
    dueDate: "2024-01-25",
  },
  {
    id: "t2",
    memberId: "2",
    memberName: "佐藤花子",
    action: "Nutrition plan review",
    status: "in progress",
    assignedTrainer: "佐々木トレーナー",
    dueDate: "2024-01-24",
  },
  {
    id: "t3",
    memberId: "3",
    memberName: "鈴木一郎",
    action: "Progress check",
    status: "done",
    assignedTrainer: "山本トレーナー",
    dueDate: "2024-01-23",
  },
  {
    id: "t4",
    memberId: "4",
    memberName: "山田次郎",
    action: "Emergency intervention",
    status: "pending",
    assignedTrainer: "佐々木トレーナー",
    dueDate: "2024-01-26",
  },
  {
    id: "t5",
    memberId: "5",
    memberName: "伊藤美咲",
    action: "Workout plan adjustment",
    status: "in progress",
    assignedTrainer: "山本トレーナー",
    dueDate: "2024-01-25",
  },
  {
    id: "t6",
    memberId: "6",
    memberName: "高橋健太",
    action: "Initial assessment",
    status: "done",
    assignedTrainer: "佐々木トレーナー",
    dueDate: "2024-01-22",
  },
  {
    id: "t7",
    memberId: "1",
    memberName: "田中太郎",
    action: "Risk assessment review",
    status: "pending",
    assignedTrainer: "山本トレーナー",
    dueDate: "2024-01-27",
  },
];

// Helper functions to get data by member ID
// 注意: これらの関数は後方互換性のために残していますが、
// 新しいコードでは lib/repositories 経由でアクセスすることを推奨します
export function getMemberById(id: string): Member | undefined {
  return members.find((member) => member.id === id);
}

export function getVisitsByMemberId(memberId: string): Visit[] {
  return visits.filter((visit) => visit.memberId === memberId);
}

export function getInterventionsByMemberId(memberId: string): Intervention[] {
  return interventions.filter((intervention) => intervention.memberId === memberId);
}

export function getTasksByMemberId(memberId: string): Task[] {
  return tasks.filter((task) => task.memberId === memberId);
}
