import { Member, Task } from "@/types";
import { calculateRiskScore } from "./riskScore";
import { getInterventionSuggestion } from "./interventionSuggestion";

/**
 * ID生成関数
 */
function generateId(): string {
  const cryptoAny = globalThis.crypto as any;
  if (cryptoAny?.randomUUID) return cryptoAny.randomUUID();
  return `task_${Date.now()}_${Math.random().toString(16).slice(2)}`;
}

/**
 * 日付文字列から指定日数後の日付を取得
 */
function getDateAfterDays(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().slice(0, 10);
}

/**
 * 高リスク会員から介入タスクを自動生成
 * @param members 会員リスト
 * @returns 生成されたタスクリスト
 */
export function generateTasksFromHighRiskMembers(members: Member[]): Task[] {
  const tasks: Task[] = [];

  for (const member of members) {
    const riskResult = calculateRiskScore(member);
    const suggestion = getInterventionSuggestion(member);

    // high risk または priority high の会員を対象
    const isHighRisk = riskResult.level === "high";
    const isHighPriority = suggestion.priority === "high";

    if (isHighRisk || isHighPriority) {
      // 期限を設定（優先度に応じて）
      let dueDate: string;
      if (suggestion.priority === "high") {
        dueDate = getDateAfterDays(3); // 高優先度は3日後
      } else if (suggestion.priority === "medium") {
        dueDate = getDateAfterDays(7); // 中優先度は7日後
      } else {
        dueDate = getDateAfterDays(14); // 低優先度は14日後
      }

      // 担当トレーナーを設定（会員に割り当てられている場合はそれを使用、なければ未割り当て）
      const assignedTrainer = member.assignedTrainer || "未割り当て";

      const task: Task = {
        id: generateId(),
        memberId: member.id,
        memberName: member.name,
        action: suggestion.action,
        status: "pending",
        assignedTrainer,
        dueDate,
        priority: suggestion.priority,
        isAutoGenerated: true,
      };

      tasks.push(task);
    }
  }

  return tasks;
}


